
#################### EJERCICIO 3 - LIBROS ####################

### GET todos los libros
GET http://localhost:8080/api/libro

### GET libro con autor completo
GET http://localhost:8080/api/libro/1

### GET libro con autor sin segundo apellido
GET http://localhost:8080/api/libro/2

### GET libro sin autor
GET http://localhost:8080/api/libro/3

### GET libro con autor sin nombre y segundo apellido en blanco
GET http://localhost:8080/api/libro/4

### GET libro que no existe 
GET http://localhost:8080/api/libro/99
