
#################### EJERCICIO 4 - RESERVAS ####################

### GET todas las reservas
GET http://localhost:8080/api/reserva

### GET reserva completa
GET http://localhost:8080/api/reserva/1

### GET reserva sin cliente
GET http://localhost:8080/api/reserva/2

### GET reserva sin habitación
GET http://localhost:8080/api/reserva/3

### GET reserva sin número de noches
GET http://localhost:8080/api/reserva/4

### GET reserva de habitación sin precio por noche
GET http://localhost:8080/api/reserva/5

### GET reserva que no existe 
GET http://localhost:8080/api/reserva/99
