
#################### EJERCICIO 5 - SERIES ####################

### GET todas las series
GET http://localhost:8080/api/serie

### GET serie completa
GET http://localhost:8080/api/serie/1

### GET serie sin categoría
GET http://localhost:8080/api/serie/2

### GET serie con lista de imágenes null
GET http://localhost:8080/api/serie/3

### GET serie sin creador y lista de imágenes vacía
GET http://localhost:8080/api/serie/4

### GET serie que no existe 
GET http://localhost:8080/api/serie/99
