
#################### EJERCICIO 5 - SERIES ####################

### GET todas las series
GET http://localhost:8080/api/serie

### GET serie id 1 (completa)
GET http://localhost:8080/api/serie/1

### GET serie id 2 (sin categoría)
GET http://localhost:8080/api/serie/2

### GET serie id 3 (lista de imágenes null)
GET http://localhost:8080/api/serie/3

### GET serie id 4 (sin creador y lista de imágenes vacía)
GET http://localhost:8080/api/serie/4

### GET serie que no existe (404)
GET http://localhost:8080/api/serie/99
